

# purpose

I started with tensors in PyTorch because they're basically the building blocks of everything in deep learning. They're like NumPy arrays but way more powerful  you can run them on GPUs and they support automatic differentiation, which is super important for training neural networks. Whether it's the data going in, the model's weights, or the gradients during training, it's all tensors. Learning how to reshape, slice, multiply, and move tensors between CPU and GPU early on is definitely going to make things easier for me later. I believe having a good grip on tensors now will save me a lot of headaches when I get into more complex stuff like CNNs, RNNs, and Transformers.



In [ ]:
import torch

# creating tensor

In [ ]:
a=torch.empty(1,3)
print(a)

tensor([[2.2331e-07, 0.0000e+00, 2.2566e-07]])


In [ ]:
type(a)

torch.Tensor

In [ ]:
# to put zero in every position of tensor
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# to put ones in every position of tensor

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# to put random values on tensor

torch.rand(2,3)

tensor([[0.2265, 0.9427, 0.8349],
        [0.2651, 0.7165, 0.9796]])

In [ ]:
# for manual seed

torch.manual_seed(23)

torch.rand(2,3)

tensor([[0.4283, 0.2889, 0.4224],
        [0.3571, 0.9577, 0.1100]])

In [ ]:
# to put manual values in tensor

torch.tensor([[1,2,3],[4,5,6],[7,8,9]])



tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#for creating a 1D tensor with values starting from start to end(exclusive), with a given step

torch.arange(1,11,1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# for Creates a 1D tensor with steps number of values evenly spaced between start and end (inclusive).

torch.linspace(0,5,5)

tensor([0.0000, 1.2500, 2.5000, 3.7500, 5.0000])

In [ ]:
# for creating a 2D identity matrix
torch.eye(2,3)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [ ]:
#Creates a tensor of the given size, filled with the given_value.

torch.full((2,3),10)

tensor([[10, 10, 10],
        [10, 10, 10]])

In [ ]:
# creates a new tensor with the same shape and data type as the input tensor ,but with uninitialized values.

a=torch.empty(3,3)

b=torch.empty_like(a)

b.shape

torch.Size([3, 3])

# Mathematical operation

In [ ]:
a=torch.rand(3,3)
print(a)


tensor([[0.6732, 0.6593, 0.1879],
        [0.4546, 0.1049, 0.7112],
        [0.7709, 0.5514, 0.0807]])


In [ ]:
# additon
add=a+ 5

#subtraction

sub=a-2

# multiplication
mul=a*100

#division
div=a/10

# mod
mod=(a*100)%2

# power
pow = a**3

print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(pow)

tensor([[5.6732, 5.6593, 5.1879],
        [5.4546, 5.1049, 5.7112],
        [5.7709, 5.5514, 5.0807]])
tensor([[-1.3268, -1.3407, -1.8121],
        [-1.5454, -1.8951, -1.2888],
        [-1.2291, -1.4486, -1.9193]])
tensor([[67.3182, 65.9313, 18.7899],
        [45.4583, 10.4891, 71.1216],
        [77.0928, 55.1383,  8.0729]])
tensor([[0.0673, 0.0659, 0.0188],
        [0.0455, 0.0105, 0.0711],
        [0.0771, 0.0551, 0.0081]])
tensor([[1.3182, 1.9313, 0.7899],
        [1.4583, 0.4891, 1.1216],
        [1.0928, 1.1383, 0.0729]])
tensor([[0.3051, 0.2866, 0.0066],
        [0.0939, 0.0012, 0.3598],
        [0.4582, 0.1676, 0.0005]])


# Element wise operations

In [ ]:
x=torch.rand(3,3)
y=torch.rand(3,3)

In [ ]:
## addition
add=x+y

## sub

sub=x+y

# mul

mul = x*y

# div
div = x/y


print(add)
print(sub)
print(mul)
print(div)

tensor([[0.9107, 1.2703, 1.1164],
        [1.2231, 1.1513, 1.5307],
        [1.3849, 0.5935, 1.1032]])
tensor([[0.9107, 1.2703, 1.1164],
        [1.2231, 1.1513, 1.5307],
        [1.3849, 0.5935, 1.1032]])
tensor([[0.1203, 0.3578, 0.2667],
        [0.3427, 0.3285, 0.5720],
        [0.4792, 0.0562, 0.1927]])
tensor([[0.2138, 0.4967, 2.2236],
        [0.5511, 0.8295, 0.7341],
        [0.9490, 0.2489, 0.2457]])


# some Function

In [ ]:
# for absoulte

a=torch.tensor([1,-10,-2])

print(torch.abs(a))

tensor([ 1, 10,  2])


In [ ]:
# for negative

print(torch.neg(a))

tensor([-1, 10,  2])


In [ ]:

# for rounding off
a=torch.tensor([1.9,3.9,1.1])
print(torch.round(a))


tensor([2., 4., 1.])


# some functions for shape and type inspection

In [ ]:
a = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
print("Tensor:", a)
print("Shape:", a.shape)
print("Dims:", a.ndim)
print("Dtype:", a.dtype)
print("Device:", a.device)

Tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
Shape: torch.Size([2, 3])
Dims: 2
Dtype: torch.float32
Device: cpu


# for mathematical operation

In [ ]:
print("Sum:", torch.sum(a))
print("Mean:", torch.mean(a))
print("Std Dev:", torch.std(a))
print("Max:", torch.max(a))
print("Min:", torch.min(a))
print("Argmax:", a.argmax())
print("Argmin:", a.argmin())

Sum: tensor(21.)
Mean: tensor(3.5000)
Std Dev: tensor(1.8708)
Max: tensor(6.)
Min: tensor(1.)
Argmax: tensor(5)
Argmin: tensor(0)


# for reshaping and size changes



In [ ]:
print("Reshape:", a.reshape(3, 2))
print("Flatten:", a.flatten())
print("Unsqueeze:", a.unsqueeze(0))
print("Squeeze:", a.unsqueeze(0).squeeze())
print("Transpose:", a.transpose(0, 1))
print("Permute:", a.permute(1, 0))  # same as transpose for 2D

Reshape: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Flatten: tensor([1., 2., 3., 4., 5., 6.])
Unsqueeze: tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
Squeeze: tensor([[1., 2., 3.],
        [4., 5., 6.]])
Transpose: tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
Permute: tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# for COMPARISON & BOOLEAN OPS

In [ ]:
print("Greater than 3:", a > 3)
print("Where >3:", torch.where(a > 3, a, torch.tensor(0.)))
print("Any > 5:", (a > 5).any())
print("All > 0:", (a > 0).all())

Greater than 3: tensor([[False, False, False],
        [ True,  True,  True]])
Where >3: tensor([[0., 0., 0.],
        [4., 5., 6.]])
Any > 5: tensor(True)
All > 0: tensor(True)


# random tensor creation



In [ ]:
print("Uniform [0,1):", torch.rand(2, 2))
print("Normal Distribution:", torch.randn(2, 2))
print("Random Ints 1-10:", torch.randint(1, 100, (2, 3)))

Uniform [0,1): tensor([[0.6621, 0.1252],
        [0.6694, 0.6640]])
Normal Distribution: tensor([[-1.7683,  0.2090],
        [ 0.1718, -0.5696]])
Random Ints 1-10: tensor([[89,  7, 38],
        [72, 49, 92]])


# Tensor opeations on GPU

In [ ]:

torch.cuda.is_available()

True

In [ ]:
# creating a new tensor on GPU

gpu = torch.device('cuda')

torch.tensor((3,3),device=gpu)

tensor([3, 3], device='cuda:0')

In [ ]:
# move tensor fro cpu to gpu


a=torch.rand(3,3) # tensor on cpu

a.to(gpu) # it will convert cpu to gpu

tensor([[0.5288, 0.8860, 0.2672],
        [0.5852, 0.0334, 0.6659],
        [0.3101, 0.1667, 0.1053]], device='cuda:0')